### ISSUE TITLE
Mstead to review design docs

### ISSUE THREAD

**Issue by vritant** [vritant/trilla#2]

**Comment by mstead** [comment]
Might be wort outlining each command and including details on what it should be doing. This would allow us to be more on the same page and make coding them easier.

i.e What's the difference between track/untrack/sync.

**Comment by mstead** [comment]
Config file example will need updating to the YAML form once my code is in place. I'll take care of that.

**Comment by mstead** [comment]
Overall, I love the idea of this project. Just need to expand a little more on the design. Might be worth creating a couple of user stories as well.
